External Home Page
christfellowshipchurch/web-app-v2 pull request #265
Opened 2021-06-08 19:40 UTC by dzwood

## What's this for? 
We want to add an external landing page for the home page when a user is not logged in.

### NOTE: a solution for the background video is still being worked out, this is just for testing purposes.
* added Text Carousel package: https://www.npmjs.com/package/react-simple-typewriter

## Demo
* Go to home page.

2021-07-08 13:15 UTC, asleepingpanda requested changes

2021-07-08 13:15 UTC, asleepingpanda commented on components/DiscoverFilterSection/DiscoverFilterSection.js
> +  console.log({ contentId });
Don't forget to remove this.

2021-07-08 13:28 UTC, dzwood commented on components/DiscoverFilterSection/DiscoverFilterSection.js
> +  console.log({ contentId });
Removed :)

2021-07-14 16:30 UTC, asleepingpanda commented
@dzwood could you update the navigation bar color to use the navy as the background instead of gray?

2021-08-04 13:33 UTC, asleepingpanda commented
Could we get the "Contact Us" buttons to open in new tabs, please

2021-08-04 14:03 UTC, dzwood commented
> @dzwood Just caught something testing. The main "I Already Attend" button looks awesome when you hover, and I would love that same `white` background to be applied to the "Watch Online" button
> ![Screen Shot 2021-08-04 at 9 07 16 AM](https://user-images.githubusercontent.com/45076058/128186410-6b0d4f3b-0a1d-495a-9fc9-92b6b2fe08f8.png)

Good Catch!

2021-11-04 14:16 UTC, asleepingpanda approved these changes

2021-11-04 14:17 UTC, merged