Content item search schema update
christfellowshipchurch/web-app-v2 pull request #324
Opened 2021-08-04 21:15 UTC by asleepingpanda

### About

### Test Instructions

### Screenshots

### Closes Tickets

### Related Tickets
[CFDP-1562]

2021-08-05 12:43 UTC, codingwithlis approved these changes

2021-08-05 14:08 UTC, dzwood commented
@asleepingpanda Are there any test instructions or screenshots for this PR? Or any info on the new type that ContentSearch is supporting?

2021-08-09 14:07 UTC, dzwood requested changes
@asleepingpanda Is there any more information we need to know before merging this code?

2021-08-10 14:05 UTC, dzwood approved these changes
Sweet! This looks great 🔥

2021-08-10 17:01 UTC, merged