Content Blocks - Adding a Video to the Layout "Content to the Right" or "Content to the Left"
christfellowshipchurch/web-app-v2 pull request #564
Opened 2023-06-28 20:38 UTC by leoalfonso14

### About
This PR changes the width of a video when content is to one of the sides (in page builder pages?) in the content block file in the ui-kit folder. The vide USED to take more space than there was and create margin on the side and the user would have to scroll to the side to see the full video, not the video is smaller (cropped) and can be seen fully and no margin is created. 

### Test Instructions
1. Go to the Cohort Content Item on Rock ( [here](https://rock.christfellowship.church/page/4212?ContentItemId=14065) ) and go into the first child item (Don't stay stuck any longer) and change the content layout from "Content above an image" to Content to the left of an image or Content to the right of an image" in order to test this changes.
2. Go to [/cohorts](https://www.christfellowship.church/cohorts) on the website and see how it used to be.
3. Go to [/cohorts](https://www.christfellowship.church/cohorts) on the testing link to see how it is with the changes.
4. DO NOT SKIP THIS - Revert the changes done in step 1 to keep the content layout as Content above an image as that is the desired layout for that content item at the moment.

### Screenshot
|How it used to be|With the changes|
|--|--|
|<img width="1236" alt="Screenshot 2023-06-28 at 4 30 46 PM" src="https://github.com/christfellowshipchurch/web-app-v2/assets/94265294/cb8c7d5a-8993-4462-946d-deb78eb020a3">|<img width="1290" alt="Screenshot 2023-06-28 at 4 30 40 PM" src="https://github.com/christfellowshipchurch/web-app-v2/assets/94265294/ce871d20-4dce-4abc-ad48-1eac02dd654c">|

### Closes Tickets
[CFDP-2625](https://christfellowshipchurch.atlassian.net/browse/CFDP-2625)

2023-06-28 21:10 UTC, dzwood requested changes

2023-06-28 21:10 UTC, dzwood commented on ui-kit/ContentBlock/ContentBlock.js
> +                width={{ _: 300, md: 400, lg: 520 }}
@leoalfonso14 This is looking great! Maybe try adding conditional here instead? 🤔 Less lines of code 😁

2023-07-05 13:49 UTC, codingwithlis approved these changes
This looks great, approved!

2023-07-05 13:54 UTC, natashasthilaire approved these changes
Looks great!

2023-07-05 14:13 UTC, dzwood approved these changes

2023-07-05 14:14 UTC, merged