Wistia Videos Not Showing on Articles
christfellowshipchurch/web-app-v2 pull request #566
Opened 2023-07-05 18:58 UTC by leoalfonso14

### About
This PR fixes a bug that prevents Wistia videos not showing on articles unless a Video Link is provided as well as adding a Wistia Project media item to the Rock Content Item. 

### Test Instructions
The Testing Wistia Video Content Item on Rock ( [here](https://rock.christfellowship.church/page/2798?ContentItemId=14422) ) has no video linked, however it does have a video attached through a Wistia Project.

1. Go to [/testing-wistia-video](https://www.christfellowship.church/articles/testing-wistia-video) on the website and see how it used to be.
2. Go to [/testing-wistia-video](https://www.christfellowship.church/articles/testing-wistia-video) on the testing link to see how it is with the changes.

### Screenshots
|Rock Content Item|How it used to be|With the changes|
|--|--|
|![Screenshot 2023-07-05 at 2 54 00 PM](https://github.com/christfellowshipchurch/web-app-v2/assets/94265294/35274fbe-23ea-4675-8125-ebf89adc099b)|

### Closes Tickets
[CFDP-2635](https://christfellowshipchurch.atlassian.net/browse/CFDP-2635)

2023-07-05 19:26 UTC, dzwood requested changes

2023-07-05 19:26 UTC, dzwood commented on components/ContentSingle/ContentVideo.js
> -        src={props.video.sources[0].uri}
@leoalfonso14 We still want to support regular video URLs as well, so we don't want to get rid of this exactly. We'll have to find a way to support both 🤔

2023-07-05 19:26 UTC, dzwood commented on components/ContentSingle/ContentVideo.js
> +  wistiaID: PropTypes.string,
Can this be `wistiaId` instead to match prop name?

2023-07-05 19:29 UTC, dzwood commented
@leoalfonso14 I updated the test item in Rock to just use a Video Link instead of Wistia item. It looks like its not working anymore, so we'll need to find a way to support both Wistia and regular Video URLs. You can see in my requested changes, super great start on this though! 👏

2023-07-06 14:51 UTC, codingwithlis approved these changes
Test passed
Findings:
-If you add a video URL in Rock it will default to the Wistia media unless there is none
-When removing Wistia media in Rock you have to remove `Media` first and then `Wistia Project`, otherwise it doesn't save my changes, this is a Rock issue I assume

2023-07-06 15:25 UTC, dzwood approved these changes
Great job in this! Working great now 🎉

2023-07-06 18:15 UTC, merged