Groups resources tags
christfellowshipchurch/web-app-v2 pull request #613
Opened 2023-09-22 18:07 UTC by leoalfonso14

### About
This PR makes the process of loading the group resources when adding them to a group faster by query them as TaggedItems when a category is selected.

_TODO: Tag all resources so they show up before merging into main_
### Test Instructions
1. Open the testing link and log in.
2. Click on your profile picture on the top right and go to your groups.
3. Open any of your groups, click on manage group and try to add a resource.
4. Compare the difference of loading speed compared to live website.

### Screenshots
<img width="1440" alt="Screenshot 2023-09-22 at 2 05 13 PM" src="https://github.com/christfellowshipchurch/web-app-v2/assets/94265294/febd8fa1-912d-420a-94b4-1d119f982ba9">

### Closes Tickets
[CFDP-2612](https://christfellowshipchurch.atlassian.net/browse/CFDP-2612)

2023-09-25 13:47 UTC, dzwood commented
Great job on this!! Next steps is to reach out to Pam and make sure that all the Resource Items are tagged properly😁

2023-09-25 13:47 UTC, codingwithlis submitted a review, later dismissed

2023-09-26 17:12 UTC, codingwithlis approved these changes

2023-09-26 18:12 UTC, dzwood approved these changes
Awesome job on this @leoalfonso14 🎉 We'll just wait for the team to finishing tagging all the resources in Rock before merging😄

2023-10-05 18:26 UTC, dzwood requested changes

2023-10-05 18:26 UTC, dzwood commented on components/GroupManage/AddResourceContent.js
@leoalfonso14 Could we add a loading state for the Categories list and each of the Tags? Sometimes when I click on a Tag the items aren't loaded yet and displays an empty dropdown:
![image](https://github.com/christfellowshipchurch/web-app-v2/assets/46049974/5ef2260e-7321-4a16-9c32-f135bd3b7daf)

We should try to disable the dropdown until the items are done loading. Also we may want to consider removing empty categories.

2023-10-05 18:28 UTC, leoalfonso14 commented on components/GroupManage/AddResourceContent.js
I will look into it, thank you!

2023-10-06 20:50 UTC, codingwithlis approved these changes

2023-10-09 13:25 UTC, dzwood approved these changes
This look awesome!! Great job on those loading states too🎉

2023-10-09 14:02 UTC, merged