Added logic to change title and copy for CF Everywhere
christfellowshipchurch/web-app-v2 pull request #622
Opened 2023-10-16 20:00 UTC by codingwithlis

### About
Added logic to change title and copy for CF Everywhere

### Test Instructions
Test link -> /locations/cf-everywhere : you should see the changes on the What to Expect section  
These changes only apply to CF Everywhere, not any other campuses. 

### Screenshots
<img width="1436" alt="Screen Shot 2023-10-16 at 3 59 05 PM" src="https://github.com/christfellowshipchurch/web-app-v2/assets/46769629/b9c9c026-0351-4670-95a5-a56818b652c4">

### Closes Tickets
[CFDP-2773](https://christfellowshipchurch.atlassian.net/jira/software/projects/CFDP/boards/2?selectedIssue=CFDP-2773)

### Related Tickets
N/A

2023-10-16 20:02 UTC, leoalfonso14 submitted a review, later dismissed
Looks good!

2023-10-18 20:18 UTC, dzwood requested changes

2023-10-18 20:18 UTC, dzwood commented on components/LocationSingle/locationData.js
What if we did this?
```
const whatToExpectData = name => {
  return {
    name,
    title: `What to Expect at ${name === 'Cf Everywhere' ? 'Christ Fellowship Everywhere' : name}`,
    htmlContent: `Here at Christ Fellowship Church in ${name === 'Cf Everywhere' ? 'Christ Fellowship Everywhere' : name}, you can expect to experience church services with uplifting worship music, encouraging messages from our pastors, special programming for your family, and opportunities for you to find people to do life with all throughout the week—it all starts here!`,
  };
};
```
Just to make it shorter without repeating the same text :)

2023-10-18 20:27 UTC, codingwithlis commented on components/LocationSingle/locationData.js
I thought about doing this but I changed the htmlContent copy too, I don't think "Here at Christ Fellowship Church in Christ Fellowship Everywhere" sounds right, but lmk what you think!

2023-10-18 20:41 UTC, codingwithlis commented on components/LocationSingle/locationData.js
Got it!

2023-10-18 20:56 UTC, dzwood approved these changes
Looks awesome 🔥

2023-10-20 13:49 UTC, merged