So Good Sisterhood Cards Fix
christfellowshipchurch/web-app-v2 pull request #668
Opened 2024-02-14 15:56 UTC by leoalfonso14

### About
This PR fixes a bug where the cards on individual season pages for sisterhood podcast were not all the same width. This PR adds a set width to mobile default card. **THIS COULD AFFECT OTHER PAGES - TEST THROUGHLY**

### Test Instructions
1. Go to the live sisterhood podcast page, scroll down and check any season, we know that seasons 2, 6, and 8 have the issue, and see that on mobile view the cards do not have equal width. [/so-good-sisterhood](https://www.christfellowship.church/so-good-sisterhood)
2. Go to the same page on the testing link [/so-good-sisterhood](/so-good-sisterhood)
3. Check that no other page views, that have cards, on mobile broke. For example `/`, `/events`, `/get-there-first`, `discover`, and `2023-christ-birthday-offering`.

### Screenshots
|Before|After|
|--|--|
|<img width="1077" alt="Screenshot 2023-09-26 at 3 13 10 PM" src="https://github.com/christfellowshipchurch/web-app-v2/assets/94265294/455fd5e9-1391-4e3f-b579-e38350530d68">|<img width="1076" alt="Screenshot 2023-09-26 at 3 13 33 PM" src="https://github.com/christfellowshipchurch/web-app-v2/assets/94265294/28bdbc0d-be78-4c4f-9c10-a9cc60feaf75">|

### Closes Tickets
[CFDP-2912](https://christfellowshipchurch.atlassian.net/browse/CFDP-2912)

2024-02-15 14:19 UTC, codingwithlis approved these changes
I tested as much as I could think of and all pages look great!

2024-03-08 14:46 UTC, codingwithlis approved these changes

2024-03-08 19:55 UTC, dzwood commented
@leoalfonso14 It looks like there's some spacing causing a gap on the right in the scroll box on mobile:
<img width="655" alt="image" src="https://github.com/christfellowshipchurch/web-app-v2/assets/46049974/8605bb0a-914e-4636-9e81-80e357886217">

We can probably solve this by adjusting the container's width to 100% on mobile to fill the screen probably and then adding the appropriate margin/sizing to the cards themselves

2024-03-08 19:56 UTC, dzwood requested changes
**accident please ignore

2024-03-08 20:20 UTC, dzwood approved these changes

2024-03-08 20:20 UTC, merged